bronze_ingestion:
  source_path: notebook/data/train.csv
  bronze_file_name: bronze_data.parquet

silver_ingestion:
  bronze_file_name: bronze_data.parquet
  silver_file_name: silver_data.parquet

gold_ingestion:
  silver_file_name: silver_data.parquet
  gold_file_name: gold_data.parquet

data_ingestion:
  gold_file_name: gold_data.parquet
  train_file_name: train.parquet
  val_file_name: val.parquet
  test_file_name: test.parquet
  full_file_name: data.parquet
  random_state: 42
  test_size: 0.2
  val_size: 0.25
  target_column: loan_default

feature_selection:
  - Employment.Type
  - PRI.CURRENT.BALANCE
  - PRIMARY.INSTAL.AMT
  - NEW.ACCTS.IN.LAST.SIX.MONTHS
  - DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS
  - AVERAGE.ACCT.AGE
  - CREDIT.HISTORY.LENGTH
  - NO.OF_INQUIRIES
  - AGE
  - PRI.DEFAULT.RATIO
  - CREDIT.UTILIZATION
  - log_disbursed_amount
  - loan_default